on:
  workflow_dispatch:
    inputs:
      websiteURL:
        description: "What Website Screen ?"
        required: true
        default: "https://tai-studio.netlify.app/"
      device:
        type: 'choice'
        description: "What device test ? (desktop/mobile)"
        required: true
        default: "desktop"
        options:
        - desktop
        - mobile

name: Page Speed
jobs:
  render:
    name: Page Speed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: sudo apt update
      - run: sudo apt upgrade
      - run: npm install
      - run: npm run speed -- --props="$WORKFLOW_INPUT" --device="${{ github.event.inputs.device }}"
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
      - uses: actions/upload-artifact@v2
        with:
          name: speed
          path: data/
